<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'demi\\gearman\\' => array($vendorDir . '/demi/php-gearman'),
);
