<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf4638c0eec1a084378a269f81ca37a8b
{
    public static $prefixLengthsPsr4 = array (
        'd' => 
        array (
            'demi\\gearman\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'demi\\gearman\\' => 
        array (
            0 => __DIR__ . '/..' . '/demi/php-gearman',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf4638c0eec1a084378a269f81ca37a8b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf4638c0eec1a084378a269f81ca37a8b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
