$(document).ready(function(){var search=new UserSearch('search-text','js-search-result','/site/ajaxSearch');
var link=$('a[href$="#search"]');
//if(search.isMobile){link.prop('href','#').on('click',function(){location.href=location.origin+'/mobile-search';});
//if(!$('i.uk-icon-power-off').length&&location.href==(location.origin+'/')){}}
//else{
    link.prop('href','#search-dlg').leanModal({'overlay':0.9,'closeButton':'.lnMod-cls-btn'}).on('click',function(){search.setSearchDefaults();});
//}
var isSafari=navigator.userAgent.indexOf('Safari')!=-1&&navigator.userAgent.indexOf('Chrome')==-1&&navigator.userAgent.indexOf('Android')==-1;if(isSafari&&!search.isMobile){$('body').css('visibility','hidden').animate({'scrollTop':$(document).height()},'fast').animate({'scrollTop':0},'fast',function(){$(this).css('visibility','visible');});}
$('#newsletter-link').click(function(){if($('#newsletter-frm').is(':visible')){$('#newsletter-frm').slideUp();}else{$('#newsletter-frm').show();$('#newsletter-frm').addClass('uk-animation-slide-bottom');document.documentElement.scrollTop=document.documentElement.scrollHeight;}});$('#newsletter-btn').click(function(){$.ajax({url:"/site/subscribe",type:"POST",data:{email:$('#newsletter-email').val()},success:function(response){var data=$.parseJSON(response);if(!(data&&data.success)){if(data.error){$('#newsletter-frm').html(data.error);setTimeout(function(){$('#newsletter-frm').slideUp();},5000);}}else{$('#newsletter-frm').html('Thank you for subscribing!');setTimeout(function(){$('#newsletter-frm').slideUp();},3000);}},});});});$(window).on('load',function(){if(!$.cookie('eu-notif')){$('.eu-notif').show();$('.eu-notif-btn').on('click',function(){$.cookie('eu-notif','true',{'expires':365});$(this).parent().remove();});}});if(!window.location.origin){window.location.origin=window.location.protocol+"//"+window.location.hostname+(window.location.port?':'+window.location.port:'');}
jQuery(document).ready(function($){$('#cart-mobile-link').off('mouseenter').on('mouseenter',function(){var modal=UIkit.modal('#cart-mobile-window');if(!modal.isActive()){$('.uk-modal-cart').css('position','relative');modal.show();}});$(document).on("click",'#cart .icon-remove-circle',function(){$.ajax({type:'POST',data:{id:$(this).data('id')},url:globals.url+'/members/shop/removeFromBag',success:function(data,textStatus,jqXHR){$("#cart").html(data);$("#count_bag").html($("#count_in_bag").val());}});return false;});$(document).on("click",'.table_cart .icon-remove-circle',function(){$.ajax({type:'POST',data:{id:$(this).data('id'),checkout:true},url:globals.url+'/members/shop/removeFromBag',success:function(data,textStatus,jqXHR){$(".tab_checkout_cart").html(data);$("#count_bag").html($("#check_count_in_bag").val());}});return false;});$(document).on("click",'.add_item',function(){location.href=globals.url+'/sell-online';return false;});$(document).on("click",'#menu_cart',function(){$("#cart").toggle();$('.scrollbar-inner').scrollbar();return false;});$(document).on("click",'#cart .close',function(){$("#cart").hide();return false;});$('li.nav-correction > a').on('mouseover',function(){if(!$(this).hasClass('currency-selector')){$(this).trigger('click',['fire_event']);}}).on('click',function(e,extra){});$(document).on("mouseover",'#navbar-collapse .navbar-main li.category_menu',function(){$(this).trigger('click');var elements=$('#navbar-collapse .navbar-main > li > a');$(elements).each(function(index){$(this).attr('style','text-decoration: none !important');});$(this).find('a').eq(0).attr('style','text-decoration: underline');});$(document).on("mouseout",'#navbar-collapse .navbar-main li.category_menu',function(){var elements=$('#navbar-collapse .navbar-main > li > a');$(elements).each(function(index){$(this).removeAttr('style');});$(this).removeClass('uk-open');$(this).attr('aria-expanded',false);});$(document).on("click",'#navbar-collapse .navbar-main li.category_menu',function(){$(this).addClass('uk-open');$(this).attr('aria-expanded',true);});});
var UserSearch=function(textfield,container,action){var search=this;search._textfield=$('#'+textfield);search._container=$('#'+container);search._action=action;try{document.createEvent('TouchEvent');search.isMobile=true;}catch(e){search.isMobile=false;}
search._textfield.on('keypress',function(e){if(e.keyCode==13){$(this).trigger('enter');e.preventDefault();}else if($(this).hasClass('search-input-error')){$(this).prop('class','search-input-normal');}}).on('enter',function(){search.start();});if(search.isMobile){search._container.removeClass().parent().addClass('mobile-view');}};UserSearch.prototype.setSearchDefaults=function(){this._textfield.prop('disabled',false).val('').focus();this._container.empty();};UserSearch.prototype.start=function(){var search=this;search._textfield.val(search._textfield.val().replace(/\\|\//g,''));if(!search._textfield.val().length){return false;}
var cache,diff;if(typeof localStorage!='undefined'&&(cache=localStorage.getItem(search._textfield.val()))){cache=JSON.parse(cache);diff=(new Date().getTime()-cache.timestamp)/60000;if(diff>15){localStorage.removeItem(search._textfield.val());}else{return this.showResultTab(cache.data);}}
search._textfield.prop('disabled','disabled');search._container.empty().html('<img src="'+location.origin+'/images/ajax.gif" />');$.post(location.origin+search._action,{'query':search._textfield.val()}).done(function(response){if(response){response=JSON.parse(response).data;if(typeof localStorage!='undefined'&&!localStorage.getItem(search._textfield.val())){try{localStorage.setItem(search._textfield.val(),JSON.stringify({'timestamp':new Date().getTime(),'data':response}));}catch(e){console.log('error: '+e.message);}}
search.showResultTab(response);}}).fail(function(){search._container.html('<p>Something wrong! Maybe incorrect search string?</p>');}).always(function(){search._textfield.prop('disabled',false).blur();});};UserSearch.prototype.showResultTab=function(response){var data='';var count=0;var tmp,key,i,hdr,icon,hcat;var html='<table id="search-result-tab">'+'<caption>'+'<i class="uk-icon-search"></i> Searching results (<span></span>):'+'</caption>'+'<thead>'+'<tr>';var headers=['Users','uk-icon-user','Categories','uk-icon-list-alt','Brands','uk-icon-briefcase','Products','uk-icon-shopping-cart'];for(key in response){icon=headers.pop();hcat=headers.pop();if(response[key].length){tmp='<td class="wb"><ul>';for(i=0;i<response[key].length;i++){if(hcat=='Brands'){var link=$('<div/>').text(response[key][i]['link']).html();}else{var link=$('<div/>').text(response[key][i]['link']).html();}
var text=$('<div/>').text(response[key][i]['name']).html();text=text.toLowerCase().indexOf(this._textfield.val().toLowerCase())!=-1&&this._textfield.val().length>1?text.replace(new RegExp('('+this._textfield.val()+')','i'),'<span>$1</span>'):text;tmp+='<li>'+'<a href="'+link.toLowerCase()+'">'+'<i class="uk-icon-chevron-right"></i> '+text+'</a>'+'</li>';count++;window.location.href=link.toLowerCase();}
tmp+='</ul></td>';hdr='<td><i class="'+icon+'"></i>'+hcat+'</td>';if(this.isMobile){tmp=hdr+tmp;}else{html+=hdr;}
data+=tmp;}}
html+='</tr>'+'</thead>'+'<tbody>'+'<tr>'+data+'</tr>'+'</tbody>'+'</table>';var tab=$('#search-result-tab');if(!count){tab.append('<tr><td colspan="4">Nothing :(</td></tr>');}else if(!this.isMobile){$('.scrollbar-inner').scrollbar();}};
var Share={'width':626,'height':400,'facebook':function(link,caption,image,description,name){var url='https://www.facebook.com/dialog/feed?'+'app_id='+globals.facebook_id+'&link='+encodeURIComponent(link)+'&name='+encodeURIComponent(name)+'&caption='+encodeURIComponent(caption)+'&picture='+encodeURIComponent(image)+'&description='+encodeURIComponent(description)+'&redirect_uri='+encodeURIComponent(document.location.origin)+'/site/share/'+'&display=popup';Share.popup(url);},'twitter':function(link,title,tags){var url='https://twitter.com/intent/tweet?'+'text='+encodeURIComponent(title)+'&url='+encodeURIComponent(link)+'&hashtags='+encodeURIComponent(tags);Share.popup(url);},'pinterest':function(link,image,description){var url='https://www.pinterest.com/pin/create/button/?'+'url='+encodeURIComponent(link)+'&media='+encodeURIComponent(image)+'&description='+encodeURIComponent(description);Share.popup(url);},'instagram':function(link,image,description){},popup:function(url){var top=(screen.height-this.height)/2;var left=(document.body.clientWidth-this.width)/2;window.open(url,'','toolbar=0,status=0,width='+this.width+',height='+this.height+',top='+top+',left='+left);}};
var eternal_session={url:null,period:null,request:function(){$.ajax({url:eternal_session.url,type:'POST'});},start:function(){if(this.url===null||this.period===null)return;setInterval(this.request,this.period);}};eternal_session.url='/eternal';eternal_session.period=600000;eternal_session.start();